default_language = "en"

ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY"
GEMMA_API_KEY = "GEMMA_API_KEY"
GEMMA_API_URL = "GEMMA_API_URL"
IMAGE_API_KEY = "IMAGE_API_KEY"
IMAGE_API_URL = "IMAGE_API_URL"

# Optional backend settings
BACKEND_HOST = "0.0.0.0"
BACKEND_PORT = 8000
